import tkinter as tk
window=tk.Tk()
window.geometry('300x400')
window.title('Calculator')
a=tk.StringVar()
b=tk.StringVar()
c=tk.StringVar()
lb1num1=tk.Label(window,text='num1')
lb1num1.place(x=20,y=100)
txtnum1=tk.Entry(window,textvariable=a)
txtnum1.place(x=70,y=100)
lb1num2=tk.Label(window,text='num2')
lb1num2.place(x=20,y=150)
txtnum2=tk.Entry(window,textvariable=b)
txtnum2.place(x=70,y=150)
lb1num3=tk.Label(window,text='result')
lb1num3.place(x=20,y=200)
txtnum3=tk.Entry(window,state=tk.DISABLED,textvariable=c)
txtnum3.place(x=70,y=200)
def add():
    m=int(a.get())+int(b.get())
    c.set(str(m))
def subract():
    m=int(a.get())-int(b.get())
    c.set(str(m))
def multiply():
    m=int(a.get())*int(b.get())
    c.set(str(m))
def divide():
    m=int(a.get())//int(b.get())
    c.set(str(m))
def square():
    m=int(a.get())**int(b.get())
    c.set(str(m))
def clear():
    a.set('')
    b.set('')
    c.set('')

btnadd1=tk.Button(window,text='Add',command=add)
btnadd1.place(x=20,y=250)
btncancel=tk.Button(window,text='Clear',command=clear)
btncancel.place(x=150,y=300)
btnsubract=tk.Button(window,text='Subract',command=subract)
btnsubract.place(x=80,y=250)
btnmul=tk.Button(window,text='Multiply',command=multiply)
btnmul.place(x=150,y=250)
btndiv=tk.Button(window,text='Divide',command=divide)
btndiv.place(x=20,y=300)
btnsqr=tk.Button(window,text='Square',command=square)
btnsqr.place(x=80,y=300)
window.mainloop()